---
swagger: '2.0'
info:
  version: 1.0.0
  title: Greeting Server
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header  
paths:
  /hello:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to World if not given
      operationId: getGreeting
      # note the "security" tag created on the restricted endpoint
      security:
        - Bearer: []
      responses:
        200:
          description: returns a greeting
          schema:
              type: string
              description: contains the actual greeting as plain text
